extends Node
## Generates docs/CONTENT.md from the live data tables.  godot --headless --path . res://tests/export_docs.tscn
func _ready() -> void:
	var out := PackedStringArray()
	out.append("# TRAFFIC JAM - content reference (generated)\n")
	out.append("Generated by `tests/export_docs.gd` from the data tables.\n")
	out.append("## Vehicles (%d)\n" % Data.units.size())
	out.append("| Rarity | Vehicle | Roles | Tags | DMG | Interval | Range | Attack | Target | Ability |")
	out.append("|---|---|---|---|---|---|---|---|---|---|")
	for u in Data.unit_list:
		out.append("| %s | %s | %s | %s | %s | %.2fs | %d | %s | %s | **%s** - %s |" % [u["rarity"], u["name"], ", ".join(u["roles"]), ", ".join(u["tags"]), str(u["dmg"]), u["interval"], u["range"], u["proj"], u["target"], u["ability"], u["ability_desc"]])
	out.append("\n## Run upgrades (%d)\n" % Data.upgrades.size())
	var cur := ""
	for up in Data.upgrades:
		if up["cat"] != cur:
			cur = up["cat"]
			out.append("\n### %s\n" % cur)
		out.append("- **%s** (%s, max %d) - %s" % [up["name"], up["rarity"], up["max"], up["desc"]])
	out.append("\n## Relics (%d)\n" % Data.relics.size())
	for r in Data.relics:
		out.append("- **%s** (%s) - %s" % [r["name"], r["rarity"], r["desc"]])
	out.append("\n## Synergies\n")
	for s in Data.synergies:
		for t in s["tiers"]:
			out.append("- **%s** (%d) - %s" % [t["name"], t["n"], t["desc"]])
	out.append("\n## Statuses\n")
	for k in Data.statuses:
		out.append("- **%s** - %s" % [Data.statuses[k]["name"], Data.statuses[k]["desc"]])
	out.append("\n## Campaign\n")
	for ch in Data.chapters:
		out.append("### Chapter %d - %s (%s)\n" % [ch["id"], ch["name"], ch["sub"]])
		out.append("Boss: %s. Enemies: %s.\n" % [Data.bosses[ch["boss"]]["name"], ", ".join(ch["pool"])])
		for l in ch["levels"]:
			out.append("- %s: %d waves%s, unlocks %s" % [l["id"], l["waves"], " + boss" if l["boss"] != "" else "", Data.units[l["unlock"]]["name"] if l["unlock"] != "" else "-"])
		out.append("")
	var f := FileAccess.open(ProjectSettings.globalize_path("res://docs/CONTENT.md"), FileAccess.WRITE)
	f.store_string("\n".join(out))
	f.close()
	print("wrote docs/CONTENT.md")
	get_tree().quit()
