// All user-visible UI strings in one place (UX_FLOW 5, for later localisation).
// The title is a placeholder name (see UX_FLOW 4.2).

export const S = {
  title: 'DUST & DRAW',
  subtitle: 'A PIXEL GUNFIGHT',
  menu: {
    duel: '>> DUEL <<',
    continueRun: '>> CONTINUE <<',
    newRun: 'NEW RUN',
    saloon: 'SALOON',
    bounties: 'BOUNTIES',
    practice: 'PRACTICE',
    settings: 'SETTINGS',
    abandonTitle: 'ABANDON RUN?',
    abandonBody: 'YOUR CURRENT RUN WILL BE LOST.',
    yes: 'YES',
    no: 'NO',
    settingsSoon: 'SETTINGS: COMING SOON',
  },
  reward: {
    title: 'CHOOSE A PERK',
    reroll: 'REROLL',
    skip: 'SKIP',
    taken: 'TAKEN',
  },
  shop: {
    title: 'GENERAL STORE',
    buy: 'BUY',
    leave: 'LEAVE',
    reroll: 'REROLL',
    sold: 'SOLD',
    pickItem: 'TAP AN ITEM',
    soldOut: 'SOLD OUT',
    cantAfford: 'NEED MORE $',
    confirm: 'CONFIRM',
    tapAgain: 'TAP AGAIN TO BUY',
  },
  results: {
    death: 'YOU DIED',
    victory: 'BOUNTY PAID',
    retry: 'RIDE AGAIN',
    cont: 'CONTINUE',
    saloon: 'SALOON',
    menu: 'MAIN MENU',
    duelsWon: 'DUELS WON',
    bestReaction: 'BEST DRAW',
    perfect: 'PERFECT DRAWS',
    region: 'REGION',
    coins: 'COINS BANKED',
    killedBy: 'KILLED BY',
    stampWin: 'PAID',
    stampDeath: 'AT LARGE',
  },
  wanted: 'WANTED',
  rarity: { common: 'COMMON', rare: 'RARE', legendary: 'LEGEND' },
} as const;
