// Builds src/data/packAssets.ts and docs/ASSET_PACK_AUDIT.md from public/assets/manifest.json.
// Every path in the registry is read from the manifest and checked on disk; nothing is invented.
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = new URL('..', import.meta.url).pathname;
const PUB = path.join(ROOT, 'public/assets');
const man = JSON.parse(fs.readFileSync(path.join(PUB, 'manifest.json'), 'utf8'));

const BOSSES = new Set(['mad_dog_mcgraw', 'undertaker', 'lady_luck', 'el_diablo']);
const ENEMIES = new Set(['rookie', 'coward', 'drunk', 'elite_bounty_hunter']);
const missing = man.files.filter((f) => !fs.existsSync(path.join(PUB, f)));
if (missing.length) { console.error('MISSING', missing); process.exit(1); }

const key = (f) => path.basename(f, '.png').replace(/^\d+_/, '');
const nested = (obj, parts, val) => { let o = obj; for (const p of parts.slice(0, -1)) o = o[p] ??= {}; o[parts.at(-1)] = val; };
const reg = { characters: {}, enemies: {}, bosses: {}, animations: man.animations, effects: {}, tiles: {}, backgrounds: {}, ui: { buttons: {}, panels: {}, icons: {} }, icons: {}, cutscenes: {}, screens: {}, fonts: {} };
for (const f of man.files) {
  const p = f.split('/');
  const rel = 'assets/' + f;
  if (p[0] === 'characters') {
    const target = p[1] === 'hero' ? reg.characters : BOSSES.has(p[1]) ? reg.bosses : ENEMIES.has(p[1]) ? reg.enemies : null;
    if (!target) throw new Error('unclassified character ' + p[1]);
    nested(target, [p[1], key(f)], rel);
  } else if (p[0] === 'fx') (reg.effects[p[1]] ??= []).push(rel);
  else if (p[0] === 'tiles') nested(reg.tiles, [p[1], key(f)], rel);
  else if (p[0] === 'backgrounds') nested(reg.backgrounds, [p[1], key(f)], rel);
  else if (p[0] === 'ui' && p[1] === 'buttons') nested(reg.ui.buttons, [p[2], key(f)], rel);
  else if (p[0] === 'ui' && p[1] === 'panels') reg.ui.panels[key(f)] = rel;
  else if (p[0] === 'ui' && p[1] === 'icons') reg.icons[key(f)] = reg.ui.icons[key(f)] = rel;
  else if (p[0] === 'cutscenes') reg.cutscenes[key(f)] = rel;
  else if (p[0] === 'screens') reg.screens[key(f)] = rel;
  else if (p[0] === 'fonts') reg.fonts[key(f)] = rel;
  else throw new Error('unclassified ' + f);
}
const ts = `// GENERATED by scripts/buildAssetRegistry.mjs from public/assets/manifest.json. Do not edit by hand.
// Every path exists on disk (checked at generation time and in tests/assetPack.test.ts).
// Paths are relative to the site base: use packUrl(path).

export const PACK_ASSETS = ${JSON.stringify(reg, null, 2)} as const;

/** Resolve a registry path against the Vite base URL (works under a subpath). */
export function packUrl(rel: string): string {
  const base = (import.meta as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
  return base.replace(/\\/?$/, '/') + rel;
}
`;
fs.writeFileSync(path.join(ROOT, 'src/data/packAssets.ts'), ts);

// Inventory
const rows = [];
const used = new Set(); // nothing in the game uses the pack yet
for (const f of man.files) {
  const m = await sharp(path.join(PUB, f)).metadata();
  rows.push({ f, w: m.width, h: m.height, a: !!m.hasAlpha, bytes: fs.statSync(path.join(PUB, f)).size });
}
const groups = {};
for (const r of rows) { const g = r.f.split('/').slice(0, r.f.startsWith('ui/') ? 2 : 1).join('/'); (groups[g] ??= []).push(r); }
let md = `# Asset pack audit (Western_Game_Assets.zip)\n\nGenerated by \`scripts/buildAssetRegistry.mjs\`. Source: \`public/assets/\` (pack layout and filenames preserved). Registry: \`src/data/packAssets.ts\`.\n\n`;
md += `Total files: ${rows.length} PNG + manifest.json + README.md + CLAUDE_IMPLEMENTATION_PROMPT.md. Total PNG bytes: ${rows.reduce((a, r) => a + r.bytes, 0)}.\n\n`;
md += `| Group | Files | Dimensions |\n|---|---|---|\n`;
for (const [g, rs] of Object.entries(groups)) { const d = [...new Set(rs.map((r) => `${r.w}x${r.h}`))].join(', '); md += `| ${g} | ${rs.length} | ${d} |\n`; }
md += `\n## Animation sequences (from manifest)\n\n`;
for (const [k, v] of Object.entries(man.animations)) md += `- ${k}: ${v.join(', ')}\n`;
md += `\n## Validation\n\n- Manifest lists ${man.files.length} files; all exist on disk; none on disk are unlisted; all PNGs decode and have alpha.\n`;
md += `- Unused assets: all ${rows.length} (the current game does not load the pack yet).\n`;
fs.writeFileSync(path.join(ROOT, 'docs/ASSET_PACK_AUDIT_GENERATED.md'), md);
console.log('registry + inventory written;', rows.length, 'assets');
