"""Art recipe for each of the 60 player vehicles: which sheet sprite it uses and how it is re-coloured.

key:  (rarity, id) -> dict(base=<sheet sprite>, hue=deg, sat=mult, val=mult, tint=(r,g,b) multiply, sx=stretch, scale=mult, alpha=0-1, flip=bool)
base names are the file stems found in assets/source/vehicles/**/vehicle_<name>_<rarity>_body.png or enemies/enemy_<name>.png or bosses/boss_<name>.png
"""
R = {}
def u(rarity, uid, base, **kw):
    R[uid] = dict(rarity=rarity, base=base, **kw)

# COMMON
u("common", "taxi", "taxi")
u("common", "compact", "compact")
u("common", "hatchback", "hatchback")
u("common", "pickup", "pickup")
u("common", "delivery_van", "delivery_van")
u("common", "city_bus", "enemy:bus", hue=135, sat=1.1)
u("common", "scooter", "enemy:motorcycle")
u("common", "family_wagon", "family_wagon")
u("common", "minivan", "family_wagon", hue=150, sat=1.2)
u("common", "courier_bike", "enemy:motorcycle", hue=165, sat=1.3)
# UNCOMMON
u("uncommon", "tow_truck", "tow_truck")
u("uncommon", "garbage_truck", "enemy:truck", hue=95, sat=1.5, val=0.85)
u("uncommon", "mail_van", "mail_van")
u("uncommon", "food_truck", "food_truck")
u("uncommon", "school_bus", "school_bus")
u("uncommon", "street_sweeper", "enemy:road_cleaner")
u("uncommon", "road_worker", "road_worker")
u("uncommon", "utility_van", "box_truck_sign", hue=75, sat=0.9)
u("uncommon", "electric_taxi", "taxi_alt", hue=150, sat=1.0)
u("uncommon", "shuttle", "enemy:bus", hue=-50, sat=0.8)
# RARE
u("rare", "police", "police")
u("rare", "ambulance", "ambulance")
u("rare", "fire_engine", "fire_engine")
u("rare", "highway_patrol", "enemy:police_chase")
u("rare", "armored_van", "enemy:armored_truck")
u("rare", "construction_truck", "construction_truck")
u("rare", "news_van", "mail_van", hue=185, sat=1.2)
u("rare", "rescue_van", "ambulance", hue=38, sat=1.4)
u("rare", "recovery_truck", "tow_truck", hue=-42, sat=1.1)
u("rare", "traffic_enforcement", "police", hue=105, sat=1.5)
# EPIC
u("epic", "swat_van", "swat_van")
u("epic", "monster_truck", "boss:monster_truck", hue=205, sat=1.0, scale=0.82)
u("epic", "limousine", "hatchback", hue=-20, sat=0.35, val=0.55, sx=1.5)
u("epic", "riot_truck", "box_truck_sign", hue=190, sat=0.35, val=0.8)
u("epic", "crane_truck", "crane_truck")
u("epic", "snowplow", "mini_tank", hue=195, sat=1.2, val=1.2)
u("epic", "race_car", "supercar", tint=(1.0, 0.45, 0.4), sat=1.0)
u("epic", "mobile_command", "mobile_command")
u("epic", "heavy_wrecker", "tow_truck", hue=210, sat=0.8, val=0.6, scale=1.08)
u("epic", "airport_rescue", "fire_engine", hue=42, sat=0.6, val=1.1)
# LEGENDARY
u("legendary", "presidential_limo", "interceptor", sat=0.45, val=0.7, sx=1.4)
u("legendary", "prototype_supercar", "supercar")
u("legendary", "heavy_rescue", "armored_dozer")
u("legendary", "military_convoy", "armored_dozer", hue=65, sat=0.9, val=0.7)
u("legendary", "experimental_ev", "rocket_car")
u("legendary", "vintage_hot_rod", "hot_rod")
u("legendary", "golden_taxi", "taxi", tint=(1.0, 0.86, 0.45), sat=1.2, val=1.12)
u("legendary", "interceptor", "interceptor")
u("legendary", "hyper_bus", "school_bus", hue=262, sat=1.0, sx=1.2)
u("legendary", "elite_fire_engine", "fire_racer")
# MYTHIC
u("mythic", "ghost_car", "compact", sat=0.2, val=1.1, tint=(0.75, 1.0, 0.95), alpha=0.72)
u("mythic", "time_traveller", "gadget_buggy")
u("mythic", "ufo", "boss:ufo", hue=120, sat=0.9, scale=0.82)
u("mythic", "mecha_vehicle", "boss:mecha", scale=0.8)
u("mythic", "possessed_ice_cream_truck", "ice_cream_truck")
u("mythic", "mini_tank", "mini_tank")
u("mythic", "quantum_taxi", "taxi", hue=165, sat=1.1, tint=(0.7, 1.0, 1.0))
u("mythic", "portal_bus", "winged_van")
u("mythic", "phantom_ambulance", "ambulance", sat=0.2, tint=(0.72, 0.62, 1.0), alpha=0.7)
u("mythic", "chrono_police", "police", hue=165, sat=1.2, tint=(0.8, 1.0, 1.0))
assert len(R) == 60, len(R)
