// GENERATED by scripts/buildAssetRegistry.mjs from public/assets/manifest.json. Do not edit by hand.
// Every path exists on disk (checked at generation time and in tests/assetPack.test.ts).
// Paths are relative to the site base: use packUrl(path).

export const PACK_ASSETS = {
  "characters": {
    "hero": {
      "idle": "assets/characters/hero/00_idle.png",
      "idle2": "assets/characters/hero/01_idle2.png",
      "draw1": "assets/characters/hero/02_draw1.png",
      "draw2": "assets/characters/hero/03_draw2.png",
      "aim": "assets/characters/hero/04_aim.png",
      "shoot1": "assets/characters/hero/05_shoot1.png",
      "shoot2": "assets/characters/hero/06_shoot2.png",
      "hit": "assets/characters/hero/07_hit.png",
      "dead": "assets/characters/hero/08_dead.png",
      "dodge": "assets/characters/hero/09_dodge.png"
    }
  },
  "enemies": {
    "rookie": {
      "idle": "assets/characters/rookie/00_idle.png",
      "idle2": "assets/characters/rookie/01_idle2.png",
      "tell": "assets/characters/rookie/02_tell.png",
      "aim": "assets/characters/rookie/03_aim.png",
      "shoot": "assets/characters/rookie/04_shoot.png",
      "hit": "assets/characters/rookie/05_hit.png",
      "dead": "assets/characters/rookie/06_dead.png"
    },
    "coward": {
      "idle": "assets/characters/coward/00_idle.png",
      "idle2": "assets/characters/coward/01_idle2.png",
      "tell": "assets/characters/coward/02_tell.png",
      "aim": "assets/characters/coward/03_aim.png",
      "shoot": "assets/characters/coward/04_shoot.png",
      "hit": "assets/characters/coward/05_hit.png",
      "dead": "assets/characters/coward/06_dead.png"
    },
    "drunk": {
      "idle": "assets/characters/drunk/00_idle.png",
      "idle2": "assets/characters/drunk/01_idle2.png",
      "tell": "assets/characters/drunk/02_tell.png",
      "aim": "assets/characters/drunk/03_aim.png",
      "shoot": "assets/characters/drunk/04_shoot.png",
      "hit": "assets/characters/drunk/05_hit.png",
      "dead": "assets/characters/drunk/06_dead.png"
    },
    "elite_bounty_hunter": {
      "idle": "assets/characters/elite_bounty_hunter/00_idle.png",
      "idle2": "assets/characters/elite_bounty_hunter/01_idle2.png",
      "tell": "assets/characters/elite_bounty_hunter/02_tell.png",
      "aim": "assets/characters/elite_bounty_hunter/03_aim.png",
      "shoot": "assets/characters/elite_bounty_hunter/04_shoot.png",
      "hit": "assets/characters/elite_bounty_hunter/05_hit.png",
      "dead": "assets/characters/elite_bounty_hunter/06_dead.png"
    }
  },
  "bosses": {
    "undertaker": {
      "idle": "assets/characters/undertaker/00_idle.png",
      "idle2": "assets/characters/undertaker/01_idle2.png",
      "attack": "assets/characters/undertaker/02_attack.png",
      "shoot": "assets/characters/undertaker/03_shoot.png",
      "hit": "assets/characters/undertaker/04_hit.png",
      "dead": "assets/characters/undertaker/05_dead.png",
      "phase": "assets/characters/undertaker/06_phase.png"
    },
    "lady_luck": {
      "idle": "assets/characters/lady_luck/00_idle.png",
      "idle2": "assets/characters/lady_luck/01_idle2.png",
      "attack": "assets/characters/lady_luck/02_attack.png",
      "shoot": "assets/characters/lady_luck/03_shoot.png",
      "hit": "assets/characters/lady_luck/04_hit.png",
      "dead": "assets/characters/lady_luck/05_dead.png",
      "phase": "assets/characters/lady_luck/06_phase.png"
    },
    "el_diablo": {
      "idle": "assets/characters/el_diablo/00_idle.png",
      "idle2": "assets/characters/el_diablo/01_idle2.png",
      "attack": "assets/characters/el_diablo/02_attack.png",
      "shoot": "assets/characters/el_diablo/03_shoot.png",
      "hit": "assets/characters/el_diablo/04_hit.png",
      "dead": "assets/characters/el_diablo/05_dead.png",
      "phase": "assets/characters/el_diablo/06_phase.png"
    },
    "mad_dog_mcgraw": {
      "idle": "assets/characters/mad_dog_mcgraw/00_idle.png",
      "idle2": "assets/characters/mad_dog_mcgraw/01_idle2.png",
      "attack": "assets/characters/mad_dog_mcgraw/02_attack.png",
      "shoot": "assets/characters/mad_dog_mcgraw/03_shoot.png",
      "hit": "assets/characters/mad_dog_mcgraw/04_hit.png",
      "dead": "assets/characters/mad_dog_mcgraw/05_dead.png",
      "phase": "assets/characters/mad_dog_mcgraw/06_phase.png"
    }
  },
  "animations": {
    "hero": [
      "idle",
      "idle2",
      "draw1",
      "draw2",
      "aim",
      "shoot1",
      "shoot2",
      "hit",
      "dead",
      "dodge"
    ],
    "rookie": [
      "idle",
      "idle2",
      "tell",
      "aim",
      "shoot",
      "hit",
      "dead"
    ],
    "coward": [
      "idle",
      "idle2",
      "tell",
      "aim",
      "shoot",
      "hit",
      "dead"
    ],
    "drunk": [
      "idle",
      "idle2",
      "tell",
      "aim",
      "shoot",
      "hit",
      "dead"
    ],
    "elite_bounty_hunter": [
      "idle",
      "idle2",
      "tell",
      "aim",
      "shoot",
      "hit",
      "dead"
    ],
    "undertaker": [
      "idle",
      "idle2",
      "attack",
      "shoot",
      "hit",
      "dead",
      "phase"
    ],
    "lady_luck": [
      "idle",
      "idle2",
      "attack",
      "shoot",
      "hit",
      "dead",
      "phase"
    ],
    "el_diablo": [
      "idle",
      "idle2",
      "attack",
      "shoot",
      "hit",
      "dead",
      "phase"
    ],
    "mad_dog_mcgraw": [
      "idle",
      "idle2",
      "attack",
      "shoot",
      "hit",
      "dead",
      "phase"
    ]
  },
  "effects": {
    "muzzle_flash": [
      "assets/fx/muzzle_flash/00.png",
      "assets/fx/muzzle_flash/01.png",
      "assets/fx/muzzle_flash/02.png"
    ],
    "bullet": [
      "assets/fx/bullet/00.png"
    ],
    "hit_spark": [
      "assets/fx/hit_spark/00.png",
      "assets/fx/hit_spark/01.png",
      "assets/fx/hit_spark/02.png"
    ],
    "dust_puff": [
      "assets/fx/dust_puff/00.png",
      "assets/fx/dust_puff/01.png",
      "assets/fx/dust_puff/02.png"
    ],
    "death_puff": [
      "assets/fx/death_puff/00.png",
      "assets/fx/death_puff/01.png",
      "assets/fx/death_puff/02.png"
    ],
    "explosion": [
      "assets/fx/explosion/00.png",
      "assets/fx/explosion/01.png",
      "assets/fx/explosion/02.png",
      "assets/fx/explosion/03.png",
      "assets/fx/explosion/04.png"
    ],
    "dynamite": [
      "assets/fx/dynamite/00.png",
      "assets/fx/dynamite/01.png",
      "assets/fx/dynamite/02.png"
    ],
    "exclamation": [
      "assets/fx/exclamation/00.png"
    ],
    "crosshair": [
      "assets/fx/crosshair/00.png"
    ],
    "playing_card": [
      "assets/fx/playing_card/00.png"
    ]
  },
  "tiles": {
    "dust_creek": {
      "sand": "assets/tiles/dust_creek/sand.png",
      "pebbles": "assets/tiles/dust_creek/pebbles.png",
      "cracks": "assets/tiles/dust_creek/cracks.png",
      "ground": "assets/tiles/dust_creek/ground.png",
      "edge": "assets/tiles/dust_creek/edge.png",
      "cliff": "assets/tiles/dust_creek/cliff.png",
      "cliff_corner": "assets/tiles/dust_creek/cliff_corner.png",
      "wood": "assets/tiles/dust_creek/wood.png",
      "floor": "assets/tiles/dust_creek/floor.png",
      "wall": "assets/tiles/dust_creek/wall.png",
      "door": "assets/tiles/dust_creek/door.png",
      "window": "assets/tiles/dust_creek/window.png",
      "cactus": "assets/tiles/dust_creek/cactus.png",
      "grass": "assets/tiles/dust_creek/grass.png",
      "rock": "assets/tiles/dust_creek/rock.png",
      "barrel": "assets/tiles/dust_creek/barrel.png",
      "crate": "assets/tiles/dust_creek/crate.png",
      "fence": "assets/tiles/dust_creek/fence.png",
      "sign": "assets/tiles/dust_creek/sign.png",
      "lantern": "assets/tiles/dust_creek/lantern.png",
      "rail": "assets/tiles/dust_creek/rail.png",
      "track": "assets/tiles/dust_creek/track.png",
      "mine": "assets/tiles/dust_creek/mine.png",
      "ladder": "assets/tiles/dust_creek/ladder.png",
      "bridge": "assets/tiles/dust_creek/bridge.png",
      "platform": "assets/tiles/dust_creek/platform.png",
      "roof": "assets/tiles/dust_creek/roof.png",
      "wagon": "assets/tiles/dust_creek/wagon.png",
      "wheel": "assets/tiles/dust_creek/wheel.png",
      "water_tower": "assets/tiles/dust_creek/water_tower.png",
      "boxcar": "assets/tiles/dust_creek/boxcar.png"
    },
    "canyon": {
      "sand": "assets/tiles/canyon/sand.png",
      "pebbles": "assets/tiles/canyon/pebbles.png",
      "cracks": "assets/tiles/canyon/cracks.png",
      "ground": "assets/tiles/canyon/ground.png",
      "edge": "assets/tiles/canyon/edge.png",
      "cliff": "assets/tiles/canyon/cliff.png",
      "cliff_corner": "assets/tiles/canyon/cliff_corner.png",
      "wood": "assets/tiles/canyon/wood.png",
      "floor": "assets/tiles/canyon/floor.png",
      "wall": "assets/tiles/canyon/wall.png",
      "door": "assets/tiles/canyon/door.png",
      "window": "assets/tiles/canyon/window.png",
      "cactus": "assets/tiles/canyon/cactus.png",
      "grass": "assets/tiles/canyon/grass.png",
      "rock": "assets/tiles/canyon/rock.png",
      "barrel": "assets/tiles/canyon/barrel.png",
      "crate": "assets/tiles/canyon/crate.png",
      "fence": "assets/tiles/canyon/fence.png",
      "sign": "assets/tiles/canyon/sign.png",
      "lantern": "assets/tiles/canyon/lantern.png",
      "rail": "assets/tiles/canyon/rail.png",
      "track": "assets/tiles/canyon/track.png",
      "mine": "assets/tiles/canyon/mine.png",
      "ladder": "assets/tiles/canyon/ladder.png",
      "bridge": "assets/tiles/canyon/bridge.png",
      "platform": "assets/tiles/canyon/platform.png",
      "roof": "assets/tiles/canyon/roof.png",
      "wagon": "assets/tiles/canyon/wagon.png",
      "wheel": "assets/tiles/canyon/wheel.png",
      "water_tower": "assets/tiles/canyon/water_tower.png",
      "boxcar": "assets/tiles/canyon/boxcar.png"
    },
    "railroad": {
      "sand": "assets/tiles/railroad/sand.png",
      "pebbles": "assets/tiles/railroad/pebbles.png",
      "cracks": "assets/tiles/railroad/cracks.png",
      "ground": "assets/tiles/railroad/ground.png",
      "edge": "assets/tiles/railroad/edge.png",
      "cliff": "assets/tiles/railroad/cliff.png",
      "cliff_corner": "assets/tiles/railroad/cliff_corner.png",
      "wood": "assets/tiles/railroad/wood.png",
      "floor": "assets/tiles/railroad/floor.png",
      "wall": "assets/tiles/railroad/wall.png",
      "door": "assets/tiles/railroad/door.png",
      "window": "assets/tiles/railroad/window.png",
      "cactus": "assets/tiles/railroad/cactus.png",
      "grass": "assets/tiles/railroad/grass.png",
      "rock": "assets/tiles/railroad/rock.png",
      "barrel": "assets/tiles/railroad/barrel.png",
      "crate": "assets/tiles/railroad/crate.png",
      "fence": "assets/tiles/railroad/fence.png",
      "sign": "assets/tiles/railroad/sign.png",
      "lantern": "assets/tiles/railroad/lantern.png",
      "rail": "assets/tiles/railroad/rail.png",
      "track": "assets/tiles/railroad/track.png",
      "mine": "assets/tiles/railroad/mine.png",
      "ladder": "assets/tiles/railroad/ladder.png",
      "bridge": "assets/tiles/railroad/bridge.png",
      "platform": "assets/tiles/railroad/platform.png",
      "roof": "assets/tiles/railroad/roof.png",
      "wagon": "assets/tiles/railroad/wagon.png",
      "wheel": "assets/tiles/railroad/wheel.png",
      "water_tower": "assets/tiles/railroad/water_tower.png",
      "boxcar": "assets/tiles/railroad/boxcar.png"
    }
  },
  "backgrounds": {
    "dust_creek": {
      "sky": "assets/backgrounds/dust_creek/sky.png",
      "far_mesas": "assets/backgrounds/dust_creek/far_mesas.png",
      "near_mesas": "assets/backgrounds/dust_creek/near_mesas.png",
      "ground": "assets/backgrounds/dust_creek/ground.png",
      "foreground": "assets/backgrounds/dust_creek/foreground.png",
      "full_scene": "assets/backgrounds/dust_creek/full_scene.png"
    },
    "canyon": {
      "sky": "assets/backgrounds/canyon/sky.png",
      "far_mesas": "assets/backgrounds/canyon/far_mesas.png",
      "near_mesas": "assets/backgrounds/canyon/near_mesas.png",
      "ground": "assets/backgrounds/canyon/ground.png",
      "foreground": "assets/backgrounds/canyon/foreground.png",
      "full_scene": "assets/backgrounds/canyon/full_scene.png"
    },
    "railroad": {
      "sky": "assets/backgrounds/railroad/sky.png",
      "far_mesas": "assets/backgrounds/railroad/far_mesas.png",
      "near_mesas": "assets/backgrounds/railroad/near_mesas.png",
      "ground": "assets/backgrounds/railroad/ground.png",
      "foreground": "assets/backgrounds/railroad/foreground.png",
      "full_scene": "assets/backgrounds/railroad/full_scene.png"
    }
  },
  "ui": {
    "buttons": {
      "play": {
        "normal": "assets/ui/buttons/play/normal.png",
        "hover": "assets/ui/buttons/play/hover.png",
        "pressed": "assets/ui/buttons/play/pressed.png",
        "disabled": "assets/ui/buttons/play/disabled.png"
      },
      "continue": {
        "normal": "assets/ui/buttons/continue/normal.png",
        "hover": "assets/ui/buttons/continue/hover.png",
        "pressed": "assets/ui/buttons/continue/pressed.png",
        "disabled": "assets/ui/buttons/continue/disabled.png"
      },
      "new_game": {
        "normal": "assets/ui/buttons/new_game/normal.png",
        "hover": "assets/ui/buttons/new_game/hover.png",
        "pressed": "assets/ui/buttons/new_game/pressed.png",
        "disabled": "assets/ui/buttons/new_game/disabled.png"
      },
      "settings": {
        "normal": "assets/ui/buttons/settings/normal.png",
        "hover": "assets/ui/buttons/settings/hover.png",
        "pressed": "assets/ui/buttons/settings/pressed.png",
        "disabled": "assets/ui/buttons/settings/disabled.png"
      },
      "back": {
        "normal": "assets/ui/buttons/back/normal.png",
        "hover": "assets/ui/buttons/back/hover.png",
        "pressed": "assets/ui/buttons/back/pressed.png",
        "disabled": "assets/ui/buttons/back/disabled.png"
      },
      "quit": {
        "normal": "assets/ui/buttons/quit/normal.png",
        "hover": "assets/ui/buttons/quit/hover.png",
        "pressed": "assets/ui/buttons/quit/pressed.png",
        "disabled": "assets/ui/buttons/quit/disabled.png"
      },
      "pause": {
        "normal": "assets/ui/buttons/pause/normal.png",
        "hover": "assets/ui/buttons/pause/hover.png",
        "pressed": "assets/ui/buttons/pause/pressed.png",
        "disabled": "assets/ui/buttons/pause/disabled.png"
      },
      "resume": {
        "normal": "assets/ui/buttons/resume/normal.png",
        "hover": "assets/ui/buttons/resume/hover.png",
        "pressed": "assets/ui/buttons/resume/pressed.png",
        "disabled": "assets/ui/buttons/resume/disabled.png"
      },
      "retry": {
        "normal": "assets/ui/buttons/retry/normal.png",
        "hover": "assets/ui/buttons/retry/hover.png",
        "pressed": "assets/ui/buttons/retry/pressed.png",
        "disabled": "assets/ui/buttons/retry/disabled.png"
      },
      "next": {
        "normal": "assets/ui/buttons/next/normal.png",
        "hover": "assets/ui/buttons/next/hover.png",
        "pressed": "assets/ui/buttons/next/pressed.png",
        "disabled": "assets/ui/buttons/next/disabled.png"
      },
      "select": {
        "normal": "assets/ui/buttons/select/normal.png",
        "hover": "assets/ui/buttons/select/hover.png",
        "pressed": "assets/ui/buttons/select/pressed.png",
        "disabled": "assets/ui/buttons/select/disabled.png"
      },
      "buy": {
        "normal": "assets/ui/buttons/buy/normal.png",
        "hover": "assets/ui/buttons/buy/hover.png",
        "pressed": "assets/ui/buttons/buy/pressed.png",
        "disabled": "assets/ui/buttons/buy/disabled.png"
      },
      "equip": {
        "normal": "assets/ui/buttons/equip/normal.png",
        "hover": "assets/ui/buttons/equip/hover.png",
        "pressed": "assets/ui/buttons/equip/pressed.png",
        "disabled": "assets/ui/buttons/equip/disabled.png"
      },
      "upgrade": {
        "normal": "assets/ui/buttons/upgrade/normal.png",
        "hover": "assets/ui/buttons/upgrade/hover.png",
        "pressed": "assets/ui/buttons/upgrade/pressed.png",
        "disabled": "assets/ui/buttons/upgrade/disabled.png"
      },
      "skip": {
        "normal": "assets/ui/buttons/skip/normal.png",
        "hover": "assets/ui/buttons/skip/hover.png",
        "pressed": "assets/ui/buttons/skip/pressed.png",
        "disabled": "assets/ui/buttons/skip/disabled.png"
      },
      "confirm": {
        "normal": "assets/ui/buttons/confirm/normal.png",
        "hover": "assets/ui/buttons/confirm/hover.png",
        "pressed": "assets/ui/buttons/confirm/pressed.png",
        "disabled": "assets/ui/buttons/confirm/disabled.png"
      },
      "cancel": {
        "normal": "assets/ui/buttons/cancel/normal.png",
        "hover": "assets/ui/buttons/cancel/hover.png",
        "pressed": "assets/ui/buttons/cancel/pressed.png",
        "disabled": "assets/ui/buttons/cancel/disabled.png"
      },
      "tutorial": {
        "normal": "assets/ui/buttons/tutorial/normal.png",
        "hover": "assets/ui/buttons/tutorial/hover.png",
        "pressed": "assets/ui/buttons/tutorial/pressed.png",
        "disabled": "assets/ui/buttons/tutorial/disabled.png"
      },
      "shop": {
        "normal": "assets/ui/buttons/shop/normal.png",
        "hover": "assets/ui/buttons/shop/hover.png",
        "pressed": "assets/ui/buttons/shop/pressed.png",
        "disabled": "assets/ui/buttons/shop/disabled.png"
      },
      "levels": {
        "normal": "assets/ui/buttons/levels/normal.png",
        "hover": "assets/ui/buttons/levels/hover.png",
        "pressed": "assets/ui/buttons/levels/pressed.png",
        "disabled": "assets/ui/buttons/levels/disabled.png"
      },
      "credits": {
        "normal": "assets/ui/buttons/credits/normal.png",
        "hover": "assets/ui/buttons/credits/hover.png",
        "pressed": "assets/ui/buttons/credits/pressed.png",
        "disabled": "assets/ui/buttons/credits/disabled.png"
      }
    },
    "panels": {
      "parchment": "assets/ui/panels/parchment.png",
      "wood": "assets/ui/panels/wood.png",
      "dark": "assets/ui/panels/dark.png",
      "dialogue": "assets/ui/panels/dialogue.png",
      "tooltip": "assets/ui/panels/tooltip.png",
      "shop": "assets/ui/panels/shop.png",
      "inventory": "assets/ui/panels/inventory.png",
      "tutorial": "assets/ui/panels/tutorial.png",
      "boss_intro": "assets/ui/panels/boss_intro.png",
      "victory": "assets/ui/panels/victory.png",
      "defeat": "assets/ui/panels/defeat.png",
      "settings": "assets/ui/panels/settings.png",
      "level_select": "assets/ui/panels/level_select.png"
    },
    "icons": {
      "heart_full": "assets/ui/icons/heart_full.png",
      "heart_empty": "assets/ui/icons/heart_empty.png",
      "coin": "assets/ui/icons/coin.png",
      "star": "assets/ui/icons/star.png",
      "bullet": "assets/ui/icons/bullet.png",
      "revolver": "assets/ui/icons/revolver.png",
      "dynamite": "assets/ui/icons/dynamite.png",
      "shield": "assets/ui/icons/shield.png",
      "speed": "assets/ui/icons/speed.png",
      "damage": "assets/ui/icons/damage.png",
      "luck": "assets/ui/icons/luck.png",
      "health": "assets/ui/icons/health.png",
      "dodge": "assets/ui/icons/dodge.png",
      "critical": "assets/ui/icons/critical.png",
      "reload": "assets/ui/icons/reload.png",
      "crosshair": "assets/ui/icons/crosshair.png",
      "map": "assets/ui/icons/map.png",
      "gear": "assets/ui/icons/gear.png",
      "audio": "assets/ui/icons/audio.png",
      "trophy": "assets/ui/icons/trophy.png",
      "lock": "assets/ui/icons/lock.png",
      "arrow_left": "assets/ui/icons/arrow_left.png",
      "arrow_right": "assets/ui/icons/arrow_right.png",
      "check": "assets/ui/icons/check.png",
      "close": "assets/ui/icons/close.png",
      "question": "assets/ui/icons/question.png",
      "wanted": "assets/ui/icons/wanted.png",
      "perk": "assets/ui/icons/perk.png",
      "shop": "assets/ui/icons/shop.png",
      "home": "assets/ui/icons/home.png"
    }
  },
  "icons": {
    "heart_full": "assets/ui/icons/heart_full.png",
    "heart_empty": "assets/ui/icons/heart_empty.png",
    "coin": "assets/ui/icons/coin.png",
    "star": "assets/ui/icons/star.png",
    "bullet": "assets/ui/icons/bullet.png",
    "revolver": "assets/ui/icons/revolver.png",
    "dynamite": "assets/ui/icons/dynamite.png",
    "shield": "assets/ui/icons/shield.png",
    "speed": "assets/ui/icons/speed.png",
    "damage": "assets/ui/icons/damage.png",
    "luck": "assets/ui/icons/luck.png",
    "health": "assets/ui/icons/health.png",
    "dodge": "assets/ui/icons/dodge.png",
    "critical": "assets/ui/icons/critical.png",
    "reload": "assets/ui/icons/reload.png",
    "crosshair": "assets/ui/icons/crosshair.png",
    "map": "assets/ui/icons/map.png",
    "gear": "assets/ui/icons/gear.png",
    "audio": "assets/ui/icons/audio.png",
    "trophy": "assets/ui/icons/trophy.png",
    "lock": "assets/ui/icons/lock.png",
    "arrow_left": "assets/ui/icons/arrow_left.png",
    "arrow_right": "assets/ui/icons/arrow_right.png",
    "check": "assets/ui/icons/check.png",
    "close": "assets/ui/icons/close.png",
    "question": "assets/ui/icons/question.png",
    "wanted": "assets/ui/icons/wanted.png",
    "perk": "assets/ui/icons/perk.png",
    "shop": "assets/ui/icons/shop.png",
    "home": "assets/ui/icons/home.png"
  },
  "cutscenes": {
    "intro": "assets/cutscenes/00_intro.png",
    "dust_creek": "assets/cutscenes/01_dust_creek.png",
    "first_duel": "assets/cutscenes/02_first_duel.png",
    "bounty_board": "assets/cutscenes/03_bounty_board.png",
    "undertaker": "assets/cutscenes/04_undertaker.png",
    "lady_luck": "assets/cutscenes/05_lady_luck.png",
    "el_diablo": "assets/cutscenes/06_el_diablo.png",
    "mad_dog": "assets/cutscenes/07_mad_dog.png",
    "final_showdown": "assets/cutscenes/08_final_showdown.png",
    "victory": "assets/cutscenes/09_victory.png",
    "game_over": "assets/cutscenes/10_game_over.png"
  },
  "screens": {
    "main_menu": "assets/screens/main_menu.png",
    "pause": "assets/screens/pause.png",
    "settings": "assets/screens/settings.png",
    "tutorial": "assets/screens/tutorial.png",
    "character_select": "assets/screens/character_select.png",
    "level_select": "assets/screens/level_select.png",
    "shop": "assets/screens/shop.png",
    "upgrades": "assets/screens/upgrades.png",
    "victory": "assets/screens/victory.png",
    "game_over": "assets/screens/game_over.png",
    "credits": "assets/screens/credits.png",
    "hud": "assets/screens/hud.png",
    "loading": "assets/screens/loading.png"
  },
  "fonts": {
    "bitmap_glyph_reference": "assets/fonts/bitmap_glyph_reference.png"
  }
} as const;

/** Resolve a registry path against the Vite base URL (works under a subpath). */
export function packUrl(rel: string): string {
  const base = (import.meta as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
  return base.replace(/\/?$/, '/') + rel;
}
